/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.view;

import com.mycompany.processing.Crawl;
import com.mycompany.processing.News;
import com.mycompany.processing.Service;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author Vu
 */
public class CrawlPanel extends javax.swing.JPanel {

    /**
     * Creates new form CrawlPanel
     */
    Service control = new Service();
    News Info=new News();
    Crawl crawl = new Crawl();
    int i=0;
    ArrayList<String> keys;
    public void Display(boolean t){
        if(t==true){
            buttonPanel.setVisible(true);
            informationPanel.setVisible(true);
            crawlButton.setVisible(false);
        }else{
            buttonPanel.setVisible(false);
            informationPanel.setVisible(false);
            crawlButton.setVisible(true);
        }
    }
    public CrawlPanel() {
        initComponents();
        
        try{
            URL link = new URL("https://i.imgur.com/UTu9deC.png");
            BufferedImage image = ImageIO.read(link);
            jLabel11.setIcon(new ImageIcon(image));
        }catch(Exception ex){
            
        }
        
        Display(false);
        titleTextField.setEditable(false);
        authorTextField.setEditable(false);
        dateTimeTextField.setEditable(false);
        typeTextField.setEditable(false);
        descriptionTextArea.setEditable(false);
        mainTextTextArea.setEditable(false);
        imgDescription.setLineWrap(false);
        
        mainTextTextArea.setLineWrap(true);
        descriptionTextArea.setLineWrap(true);
        imgDescription.setLineWrap(true);
        backwardButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        crawlButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        informationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleTextField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainTextTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateTimeTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        imgDescription = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backwardButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        photoPreview = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nhập URL:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        urlTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(urlTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 550, -1));

        crawlButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crawlButton.setText("Crawl");
        crawlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlButtonActionPerformed(evt);
            }
        });
        add(crawlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        buttonPanel.setBackground(new java.awt.Color(255,255,255,0));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        discardButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        discardButton.setText("Hủy");
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(discardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 130, -1));

        informationPanel.setBackground(new java.awt.Color(255,255,255,200));
        informationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tiêu đề:");
        informationPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        titleTextField.setColumns(20);
        titleTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleTextField.setRows(5);
        jScrollPane1.setViewportView(titleTextField);

        informationPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, 510, 43));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionTextArea.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea);

        informationPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 510, 80));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        mainTextTextArea.setColumns(20);
        mainTextTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainTextTextArea.setRows(5);
        jScrollPane3.setViewportView(mainTextTextArea);

        informationPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 600, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày đăng:");
        informationPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tác giả:");
        informationPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chủ đề:");
        informationPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nội dung:");
        informationPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mô tả:");
        informationPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        dateTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        informationPanel.add(dateTimeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, -1));

        authorTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        informationPanel.add(authorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, -1));

        typeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        informationPanel.add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 250, -1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        imgDescription.setColumns(20);
        imgDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imgDescription.setRows(5);
        jScrollPane5.setViewportView(imgDescription);

        informationPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 480, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mô tả:");
        informationPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ảnh:");
        informationPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        backwardButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backwardButton.setText("<<");
        backwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardButtonActionPerformed(evt);
            }
        });
        informationPanel.add(backwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        forwardButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forwardButton.setText(">>");
        forwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardButtonActionPerformed(evt);
            }
        });
        informationPanel.add(forwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, -1, -1));

        jScrollPane4.setViewportView(photoPreview);

        informationPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 480, 320));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        informationPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 10, 530));

        add(informationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1170, 560));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Crawl bài báo");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setText("jLabel11");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void forwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardButtonActionPerformed
        // TODO add your handling code here:
        forwardButton.setEnabled(true);
        backwardButton.setEnabled(true);
        i=i+1;
        imgDescription.setText(keys.get(i));
        try {
            String path = Info.getImgLink().get(keys.get(i));
            URL link = new URL(path);
            BufferedImage image = ImageIO.read(link);
            photoPreview.setIcon(new ImageIcon(image));
        } catch (Exception ex) {
            photoPreview.setText("ERROR");
        }
        if(i==keys.size()-1){
            forwardButton.setEnabled(false);
            backwardButton.setEnabled(true);
        }
    }//GEN-LAST:event_forwardButtonActionPerformed

    private void backwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardButtonActionPerformed
        // TODO add your handling code here:
        backwardButton.setEnabled(true);
        forwardButton.setEnabled(true);
        i=i-1;
        imgDescription.setText(keys.get(i));
        try {
            String path = Info.getImgLink().get(keys.get(i));
            URL link = new URL(path);
            BufferedImage image = ImageIO.read(link);
            photoPreview.setIcon(new ImageIcon(image));
        } catch (Exception ex) {
            photoPreview.setText("ERROR");
        }
        if(i==0){
            backwardButton.setEnabled(false);
            forwardButton.setEnabled(true);
        }
    }//GEN-LAST:event_backwardButtonActionPerformed

    private void crawlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlButtonActionPerformed
        // TODO add your handling code here:
        String url = urlTextField.getText();
        mainTextTextArea.setText("");
        photoPreview.setIcon(null);
        photoPreview.setText("");
        forwardButton.setEnabled(true);
        backwardButton.setEnabled(true);
        
        if(url.equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đường link vào");
        }else{
            try{
                Document doc = Jsoup.connect(url).get();
                Info.setWebsite(url);
                Info.setTitle(crawl.getTitle(doc));
                Info.setAuthor(crawl.getAuthor(doc));
                Info.setDescription(crawl.getDescription(doc));
                Info.setDatetime(crawl.getDateTime(doc));
                Info.setType(crawl.getType(doc));
                Info.setImgLink(crawl.getImgLink(doc));
                Info.setMainText(crawl.getMainText(doc));
                Date now= new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
                Info.setCrawlDate(dateFormat.format(now));
            }catch(IllegalArgumentException ex){
                JOptionPane.showMessageDialog(this, "Đường link không hợp lệ");
                urlTextField.setText("");
                return;
            }catch(IOException ex1){

            }
            Display(true);
            titleTextField.setText(Info.getTitle());
            authorTextField.setText(Info.getAuthor());
            dateTimeTextField.setText(Info.getDatetime());
            typeTextField.setText(Info.getType());
            descriptionTextArea.setText(Info.getDescription());
            for(int i = 0; i<Info.getMainText().size(); i++){
                mainTextTextArea.append(Info.getMainText().get(i)+"\n");
                mainTextTextArea.append("\n");
            }
            keys = new ArrayList(Info.getImgLink().keySet());
            imgDescription.setText(keys.get(i));
            backwardButton.setEnabled(false);
            try {
                if(keys.size()==1){
                    forwardButton.setEnabled(false);
                }
                String path = Info.getImgLink().get(keys.get(i));
                URL link = new URL(path);
                BufferedImage image = ImageIO.read(link);
                photoPreview.setIcon(new ImageIcon(image));
            } catch (Exception ex) {
                forwardButton.setEnabled(false);
                photoPreview.setText("ERROR");
            }
        }
    }//GEN-LAST:event_crawlButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here
        control.addNews(Info);
        Display(false);
        urlTextField.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        // TODO add your handling code here:
        Display(false);
        urlTextField.setText("");
    }//GEN-LAST:event_discardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorTextField;
    private javax.swing.JButton backwardButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton crawlButton;
    private javax.swing.JTextField dateTimeTextField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton discardButton;
    private javax.swing.JButton forwardButton;
    private javax.swing.JTextArea imgDescription;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea mainTextTextArea;
    private javax.swing.JLabel photoPreview;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea titleTextField;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
