/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.view;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Vu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    GridBagLayout layout = new GridBagLayout();
    CrawlPanel crawlPanel;
    CrawlHistoryPanel crawlHistoryPanel;
    HomePanel homePanel;
    
    class jPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(255,216,155);
            Color color2 = new Color(25,84,123);
            GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    GridBagConstraints c =new GridBagConstraints();
    
    public void setpanel(){
        c.gridx=0;
        c.gridy=0;
        c.fill=GridBagConstraints.BOTH;
    }

    
    public MainFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocation(-10,0);
        this.setTitle("VNExpress Crawler");
        try{
            URL link = new URL("https://i.imgur.com/dL3pfem.png");
            BufferedImage image = ImageIO.read(link);
            crawl.setIcon(new ImageIcon(image));
        }catch(Exception ex){
            
        }
        
        try{
            URL link = new URL("https://i.imgur.com/miEbExE.png");
            BufferedImage image = ImageIO.read(link);
            crawlHistory.setIcon(new ImageIcon(image));
        }catch(Exception ex){
            
        }
        try{
            URL link = new URL("https://i.imgur.com/150psU7.png");
            BufferedImage image = ImageIO.read(link);
            home.setIcon(new ImageIcon(image));
        }catch(Exception ex){
            
        }
        
        try{
            URL link = new URL("https://i.imgur.com/OMZb9DK.png");
            BufferedImage image = ImageIO.read(link);
            logOut.setIcon(new ImageIcon(image));
        }catch(Exception ex){
            
        }
      
        crawlPanel = new CrawlPanel();
        crawlHistoryPanel = new CrawlHistoryPanel();
        homePanel = new HomePanel();
        DynamicPanel.setLayout(layout);
        
        setpanel();
        DynamicPanel.add(crawlPanel, c);
        
        setpanel();
        DynamicPanel.add(crawlHistoryPanel, c);
        
        setpanel();
        DynamicPanel.add(homePanel, c);
        
        crawlPanel.setVisible(false);
        crawlHistoryPanel.setVisible(false);
        homePanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanel = new javax.swing.JPanel();
        MenuPanel = new jPanelGradient();
        crawl = new javax.swing.JButton();
        crawlHistory = new javax.swing.JButton();
        home = new javax.swing.JButton();
        logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(0, 0));

        DynamicPanel.setLayout(new java.awt.GridBagLayout());

        crawl.setBackground(new java.awt.Color(255, 255, 255));
        crawl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        crawl.setText("Crawl");
        crawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlActionPerformed(evt);
            }
        });

        crawlHistory.setBackground(new java.awt.Color(255, 255, 255));
        crawlHistory.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        crawlHistory.setText("Lịch sử");
        crawlHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlHistoryActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(255, 255, 255));
        logOut.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        logOut.setText("Thoát");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crawlHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(crawl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(home)
                .addGap(31, 31, 31)
                .addComponent(crawl)
                .addGap(31, 31, 31)
                .addComponent(crawlHistory)
                .addGap(31, 31, 31)
                .addComponent(logOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlActionPerformed
        // TODO add your handling code here:
        crawlPanel.setVisible(true);
        crawlHistoryPanel.setVisible(false);
        homePanel.setVisible(false);
    }//GEN-LAST:event_crawlActionPerformed

    private void crawlHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlHistoryActionPerformed
        // TODO add your handling code here:
        crawlPanel.setVisible(false);
        crawlHistoryPanel.setVisible(true);
        homePanel.setVisible(false);
    }//GEN-LAST:event_crawlHistoryActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        crawlPanel.setVisible(false);
        crawlHistoryPanel.setVisible(false);
        homePanel.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton crawl;
    private javax.swing.JButton crawlHistory;
    private javax.swing.JButton home;
    private javax.swing.JButton logOut;
    // End of variables declaration//GEN-END:variables
}
